(function(){"use strict";var devices=window.POTION_KINDLE_DEVICES||[],selector=document.getElementById("device"),orientationSelector=document.getElementById("orientation"),frame=document.getElementById("device-frame"),screen=document.getElementById("device-screen"),iframe=document.getElementById("potion"),details=document.getElementById("details"),current,orientation="portrait",fit=true;
function find(id){var i;for(i=0;i<devices.length;++i)if(devices[i].id===id)return devices[i];for(i=0;i<devices.length;++i)if(devices[i].id==="kindle-oasis-8")return devices[i];return devices[0];}
function dimensions(){return orientation==="landscape"?{width:current.height,height:current.width}:{width:current.width,height:current.height};}
function layout(){if(!current)return;var size=dimensions(),scale=fit?Math.min(1,(window.innerWidth-250)/size.width,(window.innerHeight-118)/size.height):1,status=current.statusBarHeight||40;iframe.style.width=size.width+"px";iframe.style.height=(size.height-status)+"px";document.getElementById("kindle-status").style.height=status+"px";screen.style.width=size.width+"px";screen.style.height=size.height+"px";screen.style.transform="scale("+scale+")";frame.style.width=Math.round(size.width*scale)+18+"px";frame.style.height=Math.round(size.height*scale)+18+"px";details.innerHTML=size.width+" &times; "+size.height+" &middot; "+orientation+" &middot; "+current.family+" &middot; "+Math.round(scale*100)+"%";document.getElementById("fit").innerHTML=fit?"100%":"Fit window";}
function notifyOrientation(){var view,doc,event;try{view=iframe.contentWindow;doc=iframe.contentDocument||view.document;}catch(ignored){return;}try{view.orientation=orientation==="landscape"?90:0;}catch(ignoredOrientation){}try{if(doc&&doc.createEvent){event=doc.createEvent("Event");event.initEvent("orientationchange",false,false);view.dispatchEvent(event);}}catch(ignoredEvent){}}
function select(id){current=find(id);selector.value=current.id;window.localStorage.setItem("potion_simulator_device",current.id);layout();}
function selectOrientation(value){orientation=value==="landscape"?"landscape":"portrait";orientationSelector.value=orientation;layout();window.setTimeout(notifyOrientation,0);}
function input(action){var xhr=new XMLHttpRequest();xhr.open("POST","/api/simulator/input",true);xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xhr.send("action="+action);}
function installHostFonts(){var doc,link;try{doc=iframe.contentDocument||iframe.contentWindow.document;if(!doc||!doc.head||doc.getElementById("potion-simulator-host-fonts"))return;link=doc.createElement("link");link.id="potion-simulator-host-fonts";link.rel="stylesheet";link.href="/simulator/host-fonts.css";doc.head.appendChild(link);}catch(ignored){}}
function reload(){iframe.src="/?simulator="+new Date().getTime();}
devices.forEach(function(device){var option=document.createElement("option");option.value=device.id;option.appendChild(document.createTextNode(device.label));selector.appendChild(option);});selector.onchange=function(){select(selector.value);};orientationSelector.onchange=function(){selectOrientation(orientationSelector.value);};document.getElementById("backward").onclick=function(){input("backward");};document.getElementById("forward").onclick=function(){input("forward");};document.getElementById("reload").onclick=reload;document.getElementById("fit").onclick=function(){fit=!fit;layout();};iframe.onload=function(){installHostFonts();notifyOrientation();};window.onresize=layout;document.onkeydown=function(event){event=event||window.event;if(event.target&&/input|select|textarea/i.test(event.target.tagName))return;if(event.keyCode===37||event.keyCode===33){input("backward");event.preventDefault();}else if(event.keyCode===39||event.keyCode===34){input("forward");event.preventDefault();}};select(window.localStorage.getItem("potion_simulator_device")||"kindle-oasis-8");selectOrientation("portrait");reload();}());
